import { all, get, run } from "./db";
import { fetchChannels, fetchVideos, ytFetch, QuotaExceededError, RateLimitedError } from "./youtubeClient";
import { searchWithYtdlp } from "./ytdlpSearch";
import type { ChannelInfo, VideoInfo } from "./types";
import { VIDEO_FORMATS, FORMAT_NICHES } from "./niches";

export { VIDEO_FORMATS, FORMAT_NICHES, type Niche, type VideoFormat } from "./niches";

export interface TrendingChannel {
  channelId: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  subscriberCount: number;
  viewCount: number;
  videoCount: number;
  publishedAt: string;
  videoFormat: string;
  niche: string;
  categoryName: string;
  viralScore: number;
  growthRate: number;
  viewSubRatio: number;
  recentVideoCount: number;
  avgViewsPerVideo: number;
  isNewlyCreated: boolean;
  isRapidlyGrowing: boolean;
  aiScore: number;
}

export const YOUTUBE_CATEGORIES: { id: string; name: string; order: number }[] = [
  { id: "faceless", name: "AI Faceless Channels", order: 0 },
  { id: "longform", name: "Long Form Channels", order: 0.5 },
  { id: "shortform", name: "Short Form Channels", order: 0.6 },
  { id: "1", name: "Film & Animation", order: 1 },
  { id: "2", name: "Autos & Vehicles", order: 2 },
  { id: "10", name: "Music", order: 3 },
  { id: "15", name: "Pets & Animals", order: 4 },
  { id: "17", name: "Sports", order: 5 },
  { id: "18", name: "Short Movies", order: 6 },
  { id: "19", name: "Travel & Events", order: 7 },
  { id: "20", name: "Gaming", order: 8 },
  { id: "21", name: "Videoblogging", order: 9 },
  { id: "22", name: "People & Blogs", order: 10 },
  { id: "23", name: "Comedy", order: 11 },
  { id: "24", name: "Entertainment", order: 12 },
  { id: "25", name: "News & Politics", order: 13 },
  { id: "26", name: "Howto & Style", order: 14 },
  { id: "27", name: "Education", order: 15 },
  { id: "28", name: "Science & Technology", order: 16 },
  { id: "29", name: "Nonprofits & Activism", order: 17 },
  { id: "30", name: "Movies", order: 18 },
  { id: "31", name: "Anime / Animation", order: 19 },
  { id: "32", name: "Action / Adventure", order: 20 },
  { id: "33", name: "Classics", order: 21 },
  { id: "34", name: "Comedy", order: 22 },
  { id: "35", name: "Documentary", order: 23 },
  { id: "36", name: "Drama", order: 24 },
  { id: "37", name: "Family", order: 25 },
  { id: "38", name: "Foreign", order: 26 },
  { id: "39", name: "Horror", order: 27 },
  { id: "40", name: "Sci-Fi / Fantasy", order: 28 },
  { id: "41", name: "Thriller", order: 29 },
  { id: "42", name: "Shorts", order: 30 },
  { id: "43", name: "Shows", order: 31 },
  { id: "44", name: "Trailers", order: 32 },
];

function isNewlyCreated(publishedAt: string): boolean {
  const created = new Date(publishedAt);
  const sixMonthsAgo = new Date();
  sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
  return created > sixMonthsAgo;
}

/**
 * "Rapidly growing" threshold — a channel counts as rapidly growing when its
 * recent videos average at least this many % more views than its older videos.
 * Applied to ALL niches during discovery and ranking.
 */
export const RAPID_GROWTH_THRESHOLD = 50;

export function isRapidlyGrowing(growthRate: number): boolean {
  return growthRate >= RAPID_GROWTH_THRESHOLD;
}

/**
 * Keywords that indicate a channel/video is produced with AI tooling.
 * YouTube's API exposes no "AI-generated" field, so this heuristic scans
 * descriptions, titles and tags for the tooling/content markers creators
 * typically disclose.
 */
export const AI_CONTENT_KEYWORDS = [
  "ai generated",
  "ai-generated",
  "generated by ai",
  "ai art",
  "ai voice",
  "ai narration",
  "ai narrated",
  "ai animated",
  "ai animation",
  "ai video",
  "ai story",
  "ai documentary",
  "ai history",
  "midjourney",
  "chatgpt",
  "stable diffusion",
  "runway ml",
  "elevenlabs",
  "eleven labs",
  "text to speech",
  "text-to-speech",
  "veo",
  "sora",
  "100% ai",
  "ai powered",
  "ai-powered",
];

/**
 * Best-effort "fully AI generated" detector. Returns a 0-100 likeness score:
 * - +25 per unique AI keyword found (capped at 70)
 * - +30 bonus for channels discovered through the AI-Generated Faceless niche
 * A score >= 70 is treated as AI-generated content.
 */
export const AI_GENERATED_THRESHOLD = 70;

export function detectAiGenerated(
  channel: ChannelInfo,
  videos: VideoInfo[],
  isFacelessNiche = false
): number {
  const haystack = [
    channel.description,
    ...videos.slice(0, 10).map((v) => `${v.title} ${(v.tags || []).join(" ")}`),
  ]
    .join(" ")
    .toLowerCase();

  let hits = 0;
  for (const keyword of AI_CONTENT_KEYWORDS) {
    if (haystack.includes(keyword)) hits++;
  }

  let score = Math.min(hits * 25, 70);
  if (isFacelessNiche) score += 30;
  return Math.min(score, 100);
}

export function calculateViralScore(
  channel: ChannelInfo,
  videos: VideoInfo[],
  growthRate = 0,
  newlyCreated = false
): number {
  const viewSubRatio = channel.viewCount / Math.max(channel.subscriberCount, 1);
  const avgViewsPerVideo = channel.viewCount / Math.max(channel.videoCount, 1);

  let totalEngagement = 0;
  let videoCount = 0;
  for (const video of videos.slice(0, 10)) {
    if (video.likeCount != null && video.commentCount != null && video.viewCount > 0) {
      totalEngagement += (video.likeCount + video.commentCount) / video.viewCount;
      videoCount++;
    }
  }
  const engagementRate = videoCount > 0 ? totalEngagement / videoCount : 0;

  const created = new Date(channel.publishedAt);
  const monthsOld = (Date.now() - created.getTime()) / (30 * 24 * 60 * 60 * 1000);
  const freshnessScore = Math.max(0, 100 - monthsOld * 5);

  // Ranking boost (applies to ALL niches): rapidly growing and newly created
  // channels earn extra points so they rank at the top of every niche, while
  // the remaining channels stay visible in the list.
  const growthBonus = Math.min(Math.max(growthRate, 0) / 5, 20);
  const newChannelBonus = newlyCreated ? 5 : 0;

  const score =
    Math.min(viewSubRatio * 30, 30) +
    Math.min(avgViewsPerVideo / 10000, 25) +
    Math.min(engagementRate * 250, 25) +
    Math.min(freshnessScore, 20) +
    growthBonus +
    newChannelBonus;

  return Math.round(Math.min(score, 100));
}

function calculateGrowthRate(videos: VideoInfo[]): number {
  if (videos.length < 2) return 0;
  const sorted = [...videos].sort(
    (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );
  const recent = sorted.slice(0, Math.ceil(sorted.length / 2));
  const older = sorted.slice(Math.ceil(sorted.length / 2));

  const recentAvg = recent.reduce((sum, v) => sum + v.viewCount, 0) / recent.length;
  const olderAvg = older.reduce((sum, v) => sum + v.viewCount, 0) / Math.max(older.length, 1);

  if (olderAvg === 0) return recentAvg > 0 ? 100 : 0;
  return Math.round(((recentAvg - olderAvg) / olderAvg) * 100);
}

/**
 * Free yt-dlp search emits one child process per query, so discovery stays fast
 * and gentle: cap how many queries run per niche, and honor a shared budget so a
 * full refresh spreads its searches across many niches instead of exhausting one.
 */
export const MAX_QUERIES_PER_NICHE = 6;

export async function discoverTrendingChannels(
  videoFormat: string,
  niche: string,
  maxResults = 50,
  sharedBudget?: { remaining: number }
): Promise<{ channels: TrendingChannel[]; searchesUsed: number }> {
  const oneWeekAgo = new Date();
  oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
  const publishedAfter = oneWeekAgo.toISOString();

  const nicheData = FORMAT_NICHES[videoFormat]?.find(n => n.id === niche);
  if (!nicheData) {
    console.error(`Niche ${niche} not found for format ${videoFormat}`);
    return { channels: [], searchesUsed: 0 };
  }

  const searchQueries = nicheData.queries;
  const allChannels: TrendingChannel[] = [];

  let searchesUsed = 0;

  for (const query of searchQueries) {
    if (searchesUsed >= MAX_QUERIES_PER_NICHE) break;
    if (sharedBudget && sharedBudget.remaining <= 0) {
      console.log(`Shared search budget exhausted, stopping ${videoFormat}/${niche}`);
      break;
    }

    try {
      // Free discovery backend: yt-dlp relevance search (no API key/quota) is the
      // primary path; the Data API search.list fallback only fires when yt-dlp is
      // unavailable or returns nothing. Ranking (viral score + rapid-growth/new
      // channel bonuses) decides which discovered channels float to the top.
      const ytdlp = await searchWithYtdlp(query, maxResults);
      let videoIds: string[] = [];
      if (ytdlp && ytdlp.items.length > 0) {
        const formatMatches = (v: { durationSeconds?: number }) =>
          v.durationSeconds == null ||
          (videoFormat === "longform" ? v.durationSeconds >= 480 : v.durationSeconds <= 60);
        videoIds = ytdlp.items.filter(formatMatches).map((it) => it.videoId).filter(Boolean);
      }
      if (videoIds.length === 0) {
        const searchRes = await ytFetch<{ items?: Array<{ id?: { videoId?: string } }> }>(
          "search",
          {
            part: "snippet",
            type: "video",
            q: query,
            order: "viewCount",
            publishedAfter,
            maxResults: String(Math.min(maxResults, 50)),
          },
          "search"
        );
        videoIds = (searchRes.items ?? [])
          .map((item) => item.id?.videoId)
          .filter(Boolean) as string[];
      }
      searchesUsed++;
      if (sharedBudget) sharedBudget.remaining = Math.max(0, sharedBudget.remaining - 1);

      if (videoIds.length === 0) continue;

      const videos = await fetchVideos(videoIds);

      const filteredVideos = videoFormat === "longform"
        ? videos.filter((v) => v.durationSeconds && v.durationSeconds >= 480)
        : videos.filter((v) => !v.durationSeconds || v.durationSeconds <= 60);

      const channelIds = [...new Set(filteredVideos.map((v) => v.channelId).filter(Boolean))];

      if (channelIds.length === 0) continue;

      const channels = await fetchChannels(channelIds);

      const channelVideoMap = new Map<string, VideoInfo[]>();
      for (const video of filteredVideos) {
        const existing = channelVideoMap.get(video.channelId) || [];
        existing.push(video);
        channelVideoMap.set(video.channelId, existing);
      }

      for (const channel of channels) {
        const channelVideos = channelVideoMap.get(channel.channelId) || [];
        if (channelVideos.length === 0) continue;

        const growthRate = calculateGrowthRate(channelVideos);
        const newlyCreated = isNewlyCreated(channel.publishedAt);
        const viralScore = calculateViralScore(channel, channelVideos, growthRate, newlyCreated);
        const aiScore = detectAiGenerated(channel, channelVideos, niche === "faceless");
        const viewSubRatio = channel.viewCount / Math.max(channel.subscriberCount, 1);
        const avgViewsPerVideo = channel.viewCount / Math.max(channel.videoCount, 1);

        allChannels.push({
          channelId: channel.channelId,
          title: channel.title,
          description: channel.description,
          thumbnailUrl: channel.thumbnailUrl,
          subscriberCount: channel.subscriberCount,
          viewCount: channel.viewCount,
          videoCount: channel.videoCount,
          publishedAt: channel.publishedAt,
          videoFormat,
          niche,
          categoryName: nicheData.name,
          viralScore,
          growthRate,
          viewSubRatio,
          recentVideoCount: channelVideos.length,
          avgViewsPerVideo,
          isNewlyCreated: newlyCreated,
          isRapidlyGrowing: isRapidlyGrowing(growthRate),
          aiScore,
        });
      }
    } catch (err) {
      if (err instanceof QuotaExceededError) {
        console.log(`Quota exceeded during discovery for ${videoFormat}/${niche}, stopping`);
        throw err;
      }
      if (err instanceof RateLimitedError) {
        console.log(`Rate limited during discovery for ${videoFormat}/${niche}, retrying after delay...`);
        await new Promise(r => setTimeout(r, 10000));
        continue;
      }
      console.error(`Search error for ${videoFormat}/${niche} (query: ${query}):`, err);
      continue;
    }
  }

  const uniqueChannels = Array.from(
    new Map(allChannels.map((ch) => [ch.channelId, ch])).values()
  );

  uniqueChannels.sort((a, b) => b.viralScore - a.viralScore);

  return { channels: uniqueChannels.slice(0, 20), searchesUsed };
}

export function saveTrendingChannels(channels: TrendingChannel[]) {
  const stmt = `
    INSERT INTO trending_channels (
      channel_id, title, description, thumbnail_url, subscriber_count,
      view_count, video_count, published_at, video_format, niche, category_name,
      discovered_at, viral_score, growth_rate, view_sub_ratio,
      recent_video_count, avg_views_per_video, is_newly_created, is_rapidly_growing, ai_score, last_analyzed
    ) VALUES (
      $channel_id, $title, $description, $thumbnail_url, $subscriber_count,
      $view_count, $video_count, $published_at, $video_format, $niche, $category_name,
      $discovered_at, $viral_score, $growth_rate, $view_sub_ratio,
      $recent_video_count, $avg_views_per_video, $is_newly_created, $is_rapidly_growing, $ai_score, $last_analyzed
    )
    ON CONFLICT(channel_id) DO UPDATE SET
      title = $title, description = $description, thumbnail_url = $thumbnail_url,
      subscriber_count = $subscriber_count, view_count = $view_count,
      video_count = $video_count, published_at = $published_at,
      video_format = $video_format, niche = $niche, category_name = $category_name,
      discovered_at = $discovered_at, viral_score = $viral_score,
      growth_rate = $growth_rate, view_sub_ratio = $view_sub_ratio,
      recent_video_count = $recent_video_count, avg_views_per_video = $avg_views_per_video,
      is_newly_created = $is_newly_created, is_rapidly_growing = $is_rapidly_growing,
      ai_score = $ai_score, last_analyzed = $last_analyzed
  `;

  const now = Date.now();
  for (const ch of channels) {
    run(stmt, {
      channel_id: ch.channelId,
      title: ch.title,
      description: ch.description,
      thumbnail_url: ch.thumbnailUrl,
      subscriber_count: ch.subscriberCount,
      view_count: ch.viewCount,
      video_count: ch.videoCount,
      published_at: ch.publishedAt,
      video_format: ch.videoFormat,
      niche: ch.niche,
      category_name: ch.categoryName,
      discovered_at: now,
      viral_score: ch.viralScore,
      growth_rate: ch.growthRate,
      view_sub_ratio: ch.viewSubRatio,
      recent_video_count: ch.recentVideoCount,
      avg_views_per_video: Math.round(ch.avgViewsPerVideo),
      is_newly_created: ch.isNewlyCreated ? 1 : 0,
      is_rapidly_growing: ch.isRapidlyGrowing ? 1 : 0,
      ai_score: Math.round(ch.aiScore),
      last_analyzed: 0,
    });
  }
}

export function getTrendingChannels(
  videoFormat?: string,
  niche?: string,
  limit = 20,
  offset = 0,
  aiOnly = false
): TrendingChannel[] {
  const selectColumns = `
    channel_id AS channelId,
    title,
    description,
    thumbnail_url AS thumbnailUrl,
    subscriber_count AS subscriberCount,
    view_count AS viewCount,
    video_count AS videoCount,
    published_at AS publishedAt,
    video_format AS videoFormat,
    niche,
    category_name AS categoryName,
    viral_score AS viralScore,
    growth_rate AS growthRate,
    view_sub_ratio AS viewSubRatio,
    recent_video_count AS recentVideoCount,
    avg_views_per_video AS avgViewsPerVideo,
    is_newly_created AS isNewlyCreated,
    is_rapidly_growing AS isRapidlyGrowing,
    ai_score AS aiScore,
    last_analyzed AS lastAnalyzed
  `;
  let sql = `SELECT ${selectColumns} FROM trending_channels`;
  const params: Record<string, string | number> = {};
  const conditions: string[] = [];

  if (videoFormat && videoFormat !== "all") {
    conditions.push("video_format = $video_format");
    params.video_format = videoFormat;
  }
  if (niche && niche !== "all") {
    conditions.push("niche = $niche");
    params.niche = niche;
  }
  if (aiOnly) {
    conditions.push(`ai_score >= ${AI_GENERATED_THRESHOLD}`);
  }

  if (conditions.length > 0) {
    sql += " WHERE " + conditions.join(" AND ");
  }

  // Ranking boost (all niches): newly created + rapidly growing channels rank
  // first. Mirrors the discovery-time score boost so even rows discovered
  // before the boost existed still rank correctly.
  sql += ` ORDER BY (viral_score
    + CASE WHEN is_newly_created = 1 THEN 5 ELSE 0 END
    + CASE WHEN is_rapidly_growing = 1 THEN 10 ELSE 0 END) DESC LIMIT $limit OFFSET $offset`;
  params.limit = limit;
  params.offset = offset;

  return all<TrendingChannel>(sql, params);
}

export function getTrendingChannelCount(
  videoFormat?: string,
  niche?: string,
  aiOnly = false
): number {
  let sql = "SELECT COUNT(*) as count FROM trending_channels";
  const params: Record<string, string | number> = {};
  const conditions: string[] = [];

  if (videoFormat && videoFormat !== "all") {
    conditions.push("video_format = $video_format");
    params.video_format = videoFormat;
  }
  if (niche && niche !== "all") {
    conditions.push("niche = $niche");
    params.niche = niche;
  }
  if (aiOnly) {
    conditions.push(`ai_score >= ${AI_GENERATED_THRESHOLD}`);
  }

  if (conditions.length > 0) {
    sql += " WHERE " + conditions.join(" AND ");
  }

  return get<{ count: number }>(sql, params)?.count ?? 0;
}

export function getFormatNicheCounts(): { videoFormat: string; niche: string; count: number }[] {
  return all<{ video_format: string; niche: string; count: number }>(
    "SELECT video_format, niche, COUNT(*) as count FROM trending_channels GROUP BY video_format, niche"
  ).map((r) => ({ videoFormat: r.video_format, niche: r.niche, count: r.count }));
}

export function getTrendingChannelById(channelId: string): TrendingChannel | null {
  return get<TrendingChannel>(
    `SELECT 
      channel_id AS channelId,
      title,
      description,
      thumbnail_url AS thumbnailUrl,
      subscriber_count AS subscriberCount,
      view_count AS viewCount,
      video_count AS videoCount,
      published_at AS publishedAt,
      video_format AS videoFormat,
      niche,
      category_name AS categoryName,
      viral_score AS viralScore,
      growth_rate AS growthRate,
      view_sub_ratio AS viewSubRatio,
      recent_video_count AS recentVideoCount,
      avg_views_per_video AS avgViewsPerVideo,
      is_newly_created AS isNewlyCreated,
      is_rapidly_growing AS isRapidlyGrowing,
      ai_score AS aiScore,
      last_analyzed AS lastAnalyzed
    FROM trending_channels WHERE channel_id = $channel_id`,
    { channel_id: channelId }
  ) ?? null;
}

export function logDiscovery(videoFormat: string, niche: string, channelsFound: number, searchesUsed: number) {
  run(
    `INSERT INTO discovery_log (video_format, niche, channels_found, searches_used, discovered_at)
     VALUES ($video_format, $niche, $channels_found, $searches_used, $discovered_at)`,
    {
      video_format: videoFormat,
      niche,
      channels_found: channelsFound,
      searches_used: searchesUsed,
      discovered_at: Date.now(),
    }
  );
}

export function wasNicheDiscoveredRecently(videoFormat: string, niche: string, withinMs = 24 * 60 * 60 * 1000): boolean {
  const row = get<{ discovered_at: number }>(
    `SELECT discovered_at FROM discovery_log
     WHERE video_format = $video_format AND niche = $niche AND channels_found > 0
     ORDER BY discovered_at DESC LIMIT 1`,
    { video_format: videoFormat, niche }
  );
  if (!row) return false;
  return Date.now() - row.discovered_at < withinMs;
}

export function getDiscoveryStatus(): { videoFormat: string; niche: string; lastDiscoveredAt: number; channelsFound: number }[] {
  return all<{ video_format: string; niche: string; discovered_at: number; channels_found: number }>(
    `SELECT d.video_format, d.niche, d.discovered_at, d.channels_found
     FROM discovery_log d
     INNER JOIN (
       SELECT video_format, niche, MAX(discovered_at) as max_at
       FROM discovery_log
       GROUP BY video_format, niche
     ) latest ON d.video_format = latest.video_format AND d.niche = latest.niche AND d.discovered_at = latest.max_at`
  ).map(r => ({
    videoFormat: r.video_format,
    niche: r.niche,
    lastDiscoveredAt: r.discovered_at,
    channelsFound: r.channels_found,
  }));
}

/**
 * Wall-clock budget for a full refresh: yt-dlp spawns are ~1-3s each, so several
 * dozen searches across niches complete in well under a minute running in
 * parallel. Discovered niches refresh again after 24h, so a budget keeps every
 * refresh fast while still reaching many niches.
 */
export const TOTAL_SEARCH_BUDGET = 48;

async function mapWithConcurrency<T, R>(
  items: T[],
  concurrency: number,
  fn: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i], i);
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, () => worker())
  );
  return results;
}

export async function refreshAllTrending(
  videoFormat?: string,
  niche?: string
): Promise<{ discovered: number; niches: number; searchesUsed: number }> {
  const formatsToScan = videoFormat && videoFormat !== "all"
    ? VIDEO_FORMATS.filter(f => f.id === videoFormat)
    : VIDEO_FORMATS;

  // Collect every (format, niche) pair up front so the concurrency pool can
  // spread the shared search budget across niches instead of running one fully.
  const targets: { formatId: string; nicheId: string }[] = [];
  for (const format of formatsToScan) {
    const nichesToScan = niche && niche !== "all"
      ? FORMAT_NICHES[format.id]?.filter(n => n.id === niche) || []
      : FORMAT_NICHES[format.id] || [];

    for (const n of nichesToScan) {
      if (wasNicheDiscoveredRecently(format.id, n.id)) {
        console.log(`Skipping ${format.name}/${n.name} - discovered recently (within 24h)`);
      } else {
        targets.push({ formatId: format.id, nicheId: n.id });
      }
    }
  }

  const budget = { remaining: TOTAL_SEARCH_BUDGET };
  let quotaHit = false;
  let totalDiscovered = 0;
  let nichesScanned = 0;
  let totalSearchesUsed = 0;

  await mapWithConcurrency(targets, 4, async ({ formatId, nicheId }) => {
    const formatForLog = VIDEO_FORMATS.find(f => f.id === formatId);
    const nicheData = FORMAT_NICHES[formatId]?.find(n => n.id === nicheId);
    try {
      const result = await discoverTrendingChannels(formatId, nicheId, 50, budget);
      const channels = Array.isArray(result) ? result : result.channels;
      const searchesUsed = Array.isArray(result) ? 0 : result.searchesUsed;
      saveTrendingChannels(channels);
      if (channels.length > 0) {
        logDiscovery(formatId, nicheId, channels.length, searchesUsed);
      }
      totalDiscovered += channels.length;
      totalSearchesUsed += searchesUsed;
      nichesScanned++;
    } catch (err) {
      if (err instanceof QuotaExceededError) {
        console.log(`Quota exhausted for ${formatId}/${nicheId}, stopping discovery`);
        quotaHit = true;
        throw err;
      }
      console.error(`Failed to discover channels for ${formatForLog?.name ?? formatId}/${nicheData?.name ?? nicheId}:`, err);
    }
  }).catch(() => {
    // Swallow the stopping exception; the flag below still results in an error return.
  });

  if (quotaHit) {
    throw new QuotaExceededError();
  }

  return { discovered: totalDiscovered, niches: nichesScanned, searchesUsed: totalSearchesUsed };
}
